changelog:
  categories:
    - title: Features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [bug, fix]
    - title: Maintenance
      labels: [chore, maintenance, refactor]
    - title: Documentation
      labels: [docs]
    - title: Other Changes
      labels: ["*"]
