version: '3.9'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
  app:
    image: ${IMAGE:-ghcr.io/llamasearchai/openeducation:latest}
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-3-large}
      GPT_MODEL: ${GPT_MODEL:-gpt-4o-mini}
      USE_GPT_QA: ${USE_GPT_QA:-true}
      QDRANT_URL: http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
volumes:
  qdrant_storage:

